name: aggs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_spinkit: "^4.1.2"
  http: ^0.12.0
  toast: ^0.1.5
  provider: ^4.3.3
  intl: ^0.16.1
  cached_network_image: ^2.0.0
  recase: ^3.0.0
  shared_preferences:
  image_picker:
  image_cropper: ^1.2.2
  progress_dialog: ^1.2.0
  random_string: ^2.1.0
  material_design_icons_flutter: ^3.2.3895
  google_maps_flutter: ^0.5.25
  webview_flutter: ^0.3.14+1
  geolocator: ^5.1.3
  geocoder: ^0.2.1
  font_awesome_flutter: ^8.7.0
  carousel_pro: ^1.0.0
  flutter_cache_manager: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        
    - family: Solway
      fonts:
        - asset: fonts/Solway-Bold.ttf
  